### ISSUE TITLE
unescape example @ 2.17 在字符串中处理html和xml not working on Python3.9

### ISSUE THREAD

**Issue by xiaobojiang** [yidao620c/python3-cookbook#342]
Original example
>>> s = 'Spicy &quot;Jalape&#241;o&quot.'
>>> from html.parser import HTMLParser
>>> p = HTMLParser()
>>> p.unescape(s)
'Spicy "Jalapeño".'

after Python 3.9, 'HTMLParser' object has no attribute 'unescape', this method is removed.

a working example of Python 3.9 :
s = 'Spicy &quot;Jalape&#241;o&quot.'
import html
p = html
p.unescape(s)

ref link: https://github.com/coursera-dl/coursera-dl/issues/778

**Comment by zlu27** [comment]
@xiaobojiang 
Should we add some "translator comments"?

**Comment by xiaobojiang** [comment]
good idea.
we could do it in the footer area, or add a note in below.
